name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: '20'
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Refresh Tencent Cloud CDN
        env:
          SECRET_ID: ${{ secrets.SECRETID }}
          SECRET_KEY: ${{ secrets.SECRETKEY }}
          CDN_DOMAIN: www.yiliang.me.cdn.dnsv1.com  # 这里填入你的 CDN 加速域名
        run: |
          TIMESTAMP=$(date +%s)
          NONCE=$(od -vAn -N4 -tu4 < /dev/urandom)
          SIGNATURE=$(echo -n "POSTcdn.tencentcloudapi.com/cdn/${SECRET_ID}/${TIMESTAMP}/cdn/tc3_request" | openssl dgst -sha256 -hmac "${SECRET_KEY}" | sed 's/^.* //')
          
          curl -X POST https://cdn.tencentcloudapi.com \
          -H "Content-Type: application/json" \
          -d '{
            "Action": "PurgePathCache",
            "Version": "2018-06-06",
            "SecretId": "'"${SECRET_ID}"'",
            "Timestamp": '"${TIMESTAMP}"',
            "Nonce": '"${NONCE}"',
            "SignatureMethod": "HmacSHA256",
            "Paths": ["https://'"${CDN_DOMAIN}"'/*"],
            "FlushType": "flush"
          }' \
          -H "Authorization: HMAC-SHA256 Credential=${SECRET_ID}/${TIMESTAMP}/cdn/tc3_request, SignedHeaders=content-type;host, Signature=${SIGNATURE}"
